insert into TB_Event (name, description, place, email) values ('bara', 'bar na esquinaa', 'Esquinaa', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegianaa', 'Rodizio parmegianaa','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('barb', 'bar na esquinab', 'Esquinab', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegianab', 'Rodizio parmegianab','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('barc', 'bar na esquinac', 'Esquinac', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegianac', 'Rodizio parmegianac','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bard', 'bar na esquinad', 'Esquinad', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegianad', 'Rodizio parmegianad','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bare', 'bar na esquinae', 'Esquinae', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegianae', 'Rodizio parmegianae','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('barf', 'bar na esquinaf', 'Esquinaf', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegianaf', 'Rodizio parmegianaf','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('barg', 'bar na esquinag', 'Esquinag', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegianag', 'Rodizio parmegianag','Santa Rosalia','Rodizioparmegiana@facens.br');