insert into TB_Event (name, description, place, email) values ('bar1', 'bar na esquina', 'Esquina', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegiana1', 'Rodizio parmegiana','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bar2', 'bar na esquina', 'Esquina', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegiana2', 'Rodizio parmegiana','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bar3', 'bar na esquina', 'Esquina', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegiana3', 'Rodizio parmegiana','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bar4', 'bar na esquina', 'Esquina', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegiana4', 'Rodizio parmegiana','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bar5', 'bar na esquina', 'Esquina', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegiana5', 'Rodizio parmegiana','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bar6', 'bar na esquina', 'Esquina', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegiana6', 'Rodizio parmegiana','Santa Rosalia','Rodizioparmegiana@facens.br');
insert into TB_Event (name, description, place, email) values ('bar7', 'bar na esquina', 'Esquina', 'Bar@gmail.com');
insert into TB_Event  (name, description, place, email) values ('Parmegiana7', 'Rodizio parmegiana','Santa Rosalia','Rodizioparmegiana@facens.br');